download our smaller ts!

diff --git a/usr/bin/tailscale b/usr/bin/tailscale
--- a/usr/bin/tailscale
+++ b/usr/bin/tailscale
@@ -2,9 +2,11 @@
 
 set -e
 
+repo_url="https://github.com/Ovler-Young/openwrt-tailscale-enabler"
+
 if [ ! -f /tmp/tailscale ]; then
     arch=`uname -m`
-    if [ "$arch" == "mips" ]; then
+    if [ "$arch" == "mips" || "$arch" == "mips64" ]; then
         endianness=`echo -n I | hexdump -o | awk '{ print (substr($2,6,1)=="1") ? "le" : ""; exit }'`
     elif [ "$arch" == "armv7l" ]; then
         arch=arm
@@ -14,27 +16,22 @@ if [ ! -f /tmp/tailscale ]; then
         arch=amd64
     fi
 
-    tailscale_version="1.74.0"
+    tailscale_version="1.74.1"
 
-    latest_version=`wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2`
-    if [ "$tailscale_version" != "$latest_version" ]; then
-        tailscale_version=$latest_version
-    fi
-
-    version="${tailscale_version}_${arch}${endianness}"
+    version="tailscale-small-upx-linux-${arch}${endianness}-v${tailscale_version}"
 
     echo "Downloading Tailscale ${version} .."
 
-    echo -e "tailscale_${version}/tailscale" > /tmp/tailscale_${version}_files.txt
-
-    if [ ! -f /tmp/tailscaled ]; then
-        echo -e "tailscale_${version}/tailscaled" >> /tmp/tailscale_${version}_files.txt
+    wget -O /tmp/tailscale "${repo_url}/releases/download/v${tailscale_version}/${version}"
+    if [ $? -ne 0 ]; then
+        echo "UPX version not found, trying original version.."
+        version="tailscale-small-linux-${arch}-v${tailscale_version}"
+        wget -O /tmp/tailscale "${repo_url}/v${tailscale_version}/${version}"
     fi
 
-    wget -O- https://pkgs.tailscale.com/stable/tailscale_${version}.tgz | tar x -zvf - -C /tmp -T /tmp/tailscale_${version}_files.txt
-
-    mv /tmp/tailscale_$version/* /tmp
-    rm -rf /tmp/tailscale_${version}*
+    chmod +x /tmp/tailscale
+    ln -sf /tmp/tailscale /usr/bin/tailscale
+    ln -sf /tmp/tailscale /usr/bin/tailscaled
 
     echo "Done!"
 fi
